[package]
name = "qtty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam-client = "0.5.0"
pwd-grp = "0.1.1"
s2n-quic = "1.32.0"
tokio = { version = "1.35.1", features = ["full"] }
